### ISSUE TITLE
在块内垂直居中

### ISSUE THREAD

**Issue by TCOTC** [Achuan-2/day-counter#1]
比如说组成超级块的时候，希望能垂直居中：

![image](https://github.com/Achuan-2/siyuan-widget-dayCounter/assets/78434827/607ebb94-e73a-47d4-93fd-5899904c83dc)

变成这样：

![image](https://github.com/Achuan-2/siyuan-widget-dayCounter/assets/78434827/28d940c5-b066-4b89-9a84-47a7d775ae52)

**Comment by Achuan-2** [comment]
这个应该向思源官方反馈吧，思源的图片横向分栏也是这样的，都是顶边对齐，现在思源只有水平布局的设置，可以建议横向超级块添加垂直布局的设置
现阶段可以用代码片段顶顶
```css
/* 横向超级块中图片和挂件垂直居中 */
.protyle-wysiwyg  .sb[data-sb-layout="col"]{
        align-items: center;
}

```

**Comment by Achuan-2** [comment]
提了issue：https://github.com/siyuan-note/siyuan/issues/10906

**Comment by TCOTC** [comment]
刚刚发现这个代码片段不止是把图片和挂件居中：

![5652f248e3681f89b815fb84155516fa](https://github.com/Achuan-2/siyuan-widget-dayCounter/assets/78434827/14fe2348-dee9-468e-bcd1-175b46a7a944)

**Comment by Achuan-2** [comment]
用这个吧，可能也有些问题，还是得等官方出垂直居中的布局
```css
/* 横向超级块中图片和挂件垂直居中 */
.protyle-wysiwyg  .sb[data-sb-layout="col"]:has(.img),
.protyle-wysiwyg  .sb[data-sb-layout="col"]:has(.iframe){
        align-items: center;
}
/* 防止用自定义emoj的纯文本段落也垂直居中 */
.protyle-wysiwyg  .sb[data-sb-layout="col"]:has(.img[style="max-width: 30px;"]){
        align-items: start;
}
```
